apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: instalker
stringData:
    #ENC[AES256_GCM,data:YWrvsu7N4QTI2oGxg9BsUCyKpB4ZTMH9GDF5aSojlvcY/b6CbgK7IN9DWsoqEaZG1UnnLTuQ2RIuSYu/rNAMQNEAq25Qiw==,iv:DAt7bGbHJ75qrcgnFw3XYLmSayGp0BOdY5DQgIUdbfc=,tag:AnBtgjjJrQ3CV75Gz+/05A==,type:comment]
    #ENC[AES256_GCM,data:sUeXqQnPg3tQrVCje2OXcMjVCNDaXZCAM34+Ff7p3OzAWOa7hpuNbUlE6bQJVAg7r67D9A7E7xcoly0uJpvDutFiXBPqmyYLhCx8,iv:qSESXBveGSdoGdeRrEBmENiztjPnzVpm3rFg98jbNf4=,tag:icAJJzMDx4o3ImavPOJo6Q==,type:comment]
    USERNAME: ENC[AES256_GCM,data:jzleZgae2ScwF6LYga5hPQ==,iv:TDgbLfXKHUTmPwEO3lGBOoYf8O4Y7oCWcQAO/73XcHA=,tag:pYyT2+QsA9GUsvlFqqqZkA==,type:str]
    PASSWORD: ENC[AES256_GCM,data:oTwcbdBYsIscLYSK,iv:ylgtCRVtJ/GFfCdC95lppbhaQYK2ZwV11nOkJw8/qQI=,tag:mb8r8nI6yQzJ5HxccFk5Nw==,type:str]
    IG_SESSIONID: ENC[AES256_GCM,data:wcy4r1CuQxCBKw76etDnstWtWouS+L3ux9+99Y7YPTLnlqfMnu6bzYVVnuxTs8FH0KH0Ankhf2w9dyxCioLkjo7n7AM9OLVp4Qsc4Zxg,iv:K1ngmzQR088xWCT2zf0LVRdSCOrGBllU46Fd3+HYPDw=,tag:t5lDLYk6TR+jca2YwnhoEw==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:hjggzRLCAe/VerhrA1Zcq+NwfKwPTdPIMvL0OovyPZj/tlSYo+8GkBKb936Hrw==,iv:DO52IhtHnhujZ26ae0PZzJZ082cg/23RjlL7G3b4jLw=,tag:DH31vFCQmcdJ0Slj2cR5yg==,type:str]
    CHAT_ID: ENC[AES256_GCM,data:T4//vy/HbwAu,iv:DwvvzilXiKC7dgO4N3RGdp9ma38rmsGn37+1c2SYJs4=,tag:DYqrdDQKIJbiVQScvfqJrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VEhQRGJoUVFidXNxN2ps
            dHFiOWtDajhXVTFOZk9NbXRvTmMyQTJmbFVrCmJZNTNJVitzSHZwWGxzSDZGMDU3
            bXlVSHlOS2NuVURhaUFmQ0FWUHpJam8KLS0tIE9OVElLTkhUbnM2blJ1R1hRSDdV
            eHgrRFJQN1JTSG5qYlhCbEhESUY1NWcKb2rvoOJZ+V8QnGPymFdC7hPmco2ehnbR
            rOv/jdVGllNoCgjkikO5cgEcmfVHb/ez+pG7wCwaC7CdKgDyoMTodA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T21:28:00Z"
    mac: ENC[AES256_GCM,data:5cDNIUxKZyTvvxqlD/4axHs9VrYmzsd3pe8AOkHYb7+f9iaz4EI8EzelMWTeyH0uewFoY+SHFDAk3Z0hvx79MYl8I9szxALHSe9NnIgbZiTekJih72nuOscWo6+L0pEAi5oe2P6DY2y4OwUoAs4iq/ekf7Xv0qwWoRVQSUbK1dc=,iv:PuAdFZGJdxsxRUctJdb8eBPOC5JeT3ZCvpizqU1nN4k=,tag:ImbUimIO+p6Sd+M/O0swcA==,type:str]
    version: 3.13.3
