apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: instalker
stringData:
    #ENC[AES256_GCM,data:nj2KUMdy2xpoypSrqjHqQV4D6dGpcZIofEUyzpQJY8D1LIxu9fKVXqpdjsbsc/9U8gOstfdsYB0hDPoAAk4VjbJ4qldDgw==,iv:4537iGYZM8C4dW39rfKMDiXglf9OG/ru5dVRXwC98h0=,tag:LT2Bc8XvKMi4EEvm9APHkA==,type:comment]
    #ENC[AES256_GCM,data:Pf8yq2BPq83VBskJZK/Km2iaf4OxK32vvSTap2VkthFyLlewleOS5x0MlEdt1D114ykckqGWeG+9BRPl+G2Zx0gEV7U7Gk7bZiOZ,iv:DmfrFGTmCW0XLjJq7+ovObmflLgd/Aabfjgntj7YT6M=,tag:JqVaayidTeNA1Wd/9EU+DQ==,type:comment]
    #
    #ENC[AES256_GCM,data:Pnp2nXo6gmrjSZMnFcByN6GfYeScZN5HuFnSvVpwIbBYVSTa1eNlok7wbARzAsn9dBjoQP8UFouInUWan9jGEl/4HApsOPdGJEE=,iv:t6XLbE7RmmZs0qq69ufjMHbSHb5Ui/CLUz2KOuhvTx8=,tag:UlKZ5t7z7vtBTN11dfXoCw==,type:comment]
    #ENC[AES256_GCM,data:G7rA3NIYk12Zs5/+PJLWXbBdsxAJN0edQUjz79aOLMFno22S+583Nutt0QkadlV/gdrUo+y5B6tyvjIvTV5tFcSrvq0z2fm0GNOsQA==,iv:VSLazAvHfWwhnZPDKrEqKaY2y124vMQWklskZkHHY9E=,tag:1kdvSvqidBetlb2WTiJGvQ==,type:comment]
    USERNAME: ENC[AES256_GCM,data:8Icvo36kS/DtUze3Z+CWAA==,iv:eYbPzkReDvMBBAGBywMBl6HUltP50r52LyLrRzz3FKI=,tag:v0yfAUxhDpOMVkBNst6z3w==,type:str]
    PASSWORD: ENC[AES256_GCM,data:5R7Vl+qUp1tUHLwF,iv:6P5LG2d8sMuaPGWp4zx3difSxIah/KjW25DDZ4n56W4=,tag:qgBgwI4h4eO306CpCTePwA==,type:str]
    IG_SESSIONID: ENC[AES256_GCM,data:EyZyqe4QF+JRN9VAy01LF/3c+SkX+YaTZ+w7EokAulTDxF0IZGQVX7C64wcuYuharE/K7KDhCJ3kBGCflLWGdU5bQyvLNlZtnb9wAVkJ,iv:ZTRnFu/ji9BNVxju2NgPY9qxdhm+o0HVCRezI+HGr+w=,tag:lSbJ1mZoKRSwnLcPluCg4A==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:G/nzRkSWsaaNLKjJFYwxmYcEg5VBNo4oodX8D7koE8a4ce7GTR9pUgY7VcESqA==,iv:qhyJiF2APreK1/3Wh+SHlf+ATASEZ7fc8zBT7M+wH7Y=,tag:5Av6CogcK3o/NFBuhTaqaA==,type:str]
    CHAT_ID: ENC[AES256_GCM,data:iW534w1jxI3y,iv:LrmLYR16F8UVCNz7mBSAvZs8iRlj1gmegBliMXrIuO0=,tag:YfY1lxkGcbucWmG3F1jMFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd0lkYTI5RVhQWWVyTC9V
            RkR3by91UzZpK1NYTnhHYWVmS3FKcSt2MFhVCjBOcEhkZjArWTVsRzNTOHdMRmY1
            c3ZQbnQ4TGRPaGhtME85Wmt5dnpRTjQKLS0tIE9md1dIYU1NenRqZUdHYlJBblV2
            NEE1QVJ1eG40OGQxa0V1ZE9PbS9wdWsKMkac0b0kZPaxMOEqM85dhb+2BtcR6wot
            M/q7XpXDVNCm1Qo9N+27Tgu6FdzTRenlNN1samaeuSdTfyPv0Tq2Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T11:12:36Z"
    mac: ENC[AES256_GCM,data:1FPOQ27lD26iSsJoKgztcfeL0UCIgxTTWgde+eo3HaGyi5cfgVkO6wLp2N7CC2RfiiXHF8GVAurzvT8MgphsA9XXew6MlGB6Eka05B5n9aP3IFBcbsPvSN+tILV9fVkyzpR3Qnuv6Bz1OKjdELzWN4gGzy2TB/F7gKy79eJ8nfQ=,iv:JICug8ygh9O3mui4h2JwG/rFdQJ0+fEWMVpzmTcQ2v4=,tag:mJwa5QKWxb59nxY7Ux82sQ==,type:str]
    version: 3.13.3
