apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: instalker
stringData:
    #ENC[AES256_GCM,data:5TEZhdun2VGJtNysRRuSo2AKCCHRTztSGY/kHxrrZI0maT6P7FoKcBXLuVder3QPAwbqjxjHERU6XizQTq9lqt0IEAsuBg==,iv:rhr3F+BbhcLN0qyt/iGk99Vaujj3JXsIYaok6sU/69E=,tag:gXEzZv2vcJmgoZ7KpGl+Aw==,type:comment]
    #ENC[AES256_GCM,data:/rBLr8epU7k7axtEqM9qqEs67HApSHS5r8vmIQ558jAqFzPyVdDHwRWse00p8tnb8yQXepIv/EhZHZapoR3yf9vouEuiOxcQ7YEd,iv:3n0mJuxP4ICziUQJMw4LvyjXy43YXS5g0xHPVD303hQ=,tag:sUyeJfn0YlLtuNDaDjRgHQ==,type:comment]
    USERNAME: ENC[AES256_GCM,data:AFOV7CXAMG6GlY55eX2RuA==,iv:eTBeLpmEKDPX6Nh9/T7y957SNosw2DGWtm7nHdXtIWE=,tag:AhHINdv8VDuTVojmbdx8bg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:d0nFKTGkcLM+V5lw,iv:kfyPeGvmGKzB8euobwYP5gLXBMrsBXrpTXi2yE6A71Y=,tag:yh5vOr7XoXvkdBzBu3txuw==,type:str]
    IG_SESSIONID: ENC[AES256_GCM,data:4wDBo78sGvjqo9vLS8pbFVs16esaxHH81jmkzz4HRt9AvJVswocy4A7lnDOaFYlo5Ad2TShzIr6M6cqVpz9+449PwyTydCyiiaraLoR8,iv:Xh8h72JNkLqCRx97V7iwUUuKU0q3LzNqY2vVnbYJIDg=,tag:LaZWP66fRhj9HJ+zxlFMTQ==,type:str]
    BOT_TOKEN: ENC[AES256_GCM,data:CHzxJFfy1tpVJwhXxk6fMDoLqX5C08aWrx0ILKkCos9JLbpIEBMY0UwYeI7eQg==,iv:0xm9miGe0p0TrwxfyMcXrZvECcgfHfhKM9KQlT3/j/0=,tag:M/o5EUrcoL1SLXfwE7r85w==,type:str]
    CHAT_ID: ENC[AES256_GCM,data:3f6+9bG9EouD,iv:iIGA8vtHlhA8U/A73A5reqhoXU94nNLxLF0NtF5J2ks=,tag:p9bvwUSTrqifeOFQ7iLiyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdWxodHhRdUlheUxMV1lH
            UjB4dXprVU44QjFLb0d1YW5XVXNCZ2VxdVhVCmRZdUZyOGdrSzloUk93V1VYV0JY
            dUpHQkRxWVRUekl0enlIMWRaTXc4dW8KLS0tIFovK2FVTTRIK21kQ2dZSFB1K29v
            RVBjaXhZeXlqMEorcTJLeTNHQ1VHSWMKxGLUo9DZjbfdFHPB0c3MSuPXgB0ZT6v8
            KMSsytNrL8RoND0CCcAP+wAQAza4vMA0OHYH0YSl2pSjFscbfNVAPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T12:25:04Z"
    mac: ENC[AES256_GCM,data:JXaZXkoauLmBK2hbLtMG9BYCCm1EklkNtKFFt6ZCObSOBzlMgvDl6bjLv5vJLF9ikULPWMDB6XMvXHQWpATOOq1xQ0Gi4Y7w3WVANYm8W9JnsAFD5rdFH15sFYgqlfyaA5WWR0gUsWufPpihVwj2yAPR6PpHp0oO+HIdU+Vz+Xg=,iv:L5j1Ze1jtpBDtypgC1+mukR6OxkfmtrKqL17uK1TwXs=,tag:7VxZjvEqZHfOMVlcRQM/ig==,type:str]
    version: 3.13.2
