apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instalker-data
  namespace: instalker
  labels:
    app: instalker
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
